//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventories.Models
{
    using System;
    
    public partial class GetAdjustmentItemData_Result1
    {
        public Nullable<int> ItemId { get; set; }
        public int FTailId { get; set; }
        public Nullable<int> ItemNetQuantity { get; set; }
        public string Name { get; set; }
        public string AdjustmentNumber { get; set; }
    }
}
