//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventories.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoriesEntities : DbContext
    {
        public InventoriesEntities()
            : base("name=InventoriesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblAccessLevel> tblAccessLevels { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblContact> tblContacts { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblUnit> tblUnits { get; set; }
        public virtual DbSet<tblWarehouse> tblWarehouses { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
        public virtual DbSet<tblTransfer> tblTransfers { get; set; }
        public virtual DbSet<tblTransferItem> tblTransferItems { get; set; }
        public virtual DbSet<tblTempPath> tblTempPaths { get; set; }
        public virtual DbSet<tblCheckin> tblCheckins { get; set; }
        public virtual DbSet<tblCheckinItem> tblCheckinItems { get; set; }
        public virtual DbSet<tblCheckout> tblCheckouts { get; set; }
        public virtual DbSet<tblCheckoutItem> tblCheckoutItems { get; set; }
        public virtual DbSet<tblAdjustment> tblAdjustments { get; set; }
        public virtual DbSet<tblAdjustmentItem> tblAdjustmentItems { get; set; }
        public virtual DbSet<tblEmailSetting> tblEmailSettings { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblUserWarehouse> tblUserWarehouses { get; set; }
        public virtual DbSet<tblAlertQty> tblAlertQties { get; set; }
    
        public virtual ObjectResult<string> TransfrNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TransfrNumber");
        }
    
        public virtual ObjectResult<string> CheckinNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CheckinNumber");
        }
    
        public virtual ObjectResult<string> CheckoutNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CheckoutNumber");
        }
    
        public virtual ObjectResult<string> AdjustmentNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AdjustmentNumber");
        }
    
        public virtual ObjectResult<CheckinReportData_Result2> CheckinReportData(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckinReportData_Result2>("CheckinReportData", searchValueParameter);
        }
    
        public virtual ObjectResult<CheckoutReportData_Result> CheckoutReportData(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckoutReportData_Result>("CheckoutReportData", searchValueParameter);
        }
    
        public virtual ObjectResult<TransferReportData_Result> TransferReportData(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TransferReportData_Result>("TransferReportData", searchValueParameter);
        }
    
        public virtual ObjectResult<AdjustmentReportData_Result> AdjustmentReportData(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdjustmentReportData_Result>("AdjustmentReportData", searchValueParameter);
        }
    
        public virtual ObjectResult<GetCheckinList_Result1> GetCheckinList(Nullable<int> itemId, Nullable<int> warehouseId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var warehouseIdParameter = warehouseId.HasValue ?
                new ObjectParameter("WarehouseId", warehouseId) :
                new ObjectParameter("WarehouseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCheckinList_Result1>("GetCheckinList", itemIdParameter, warehouseIdParameter);
        }
    
        public virtual ObjectResult<GetAdjustmentItemData_Result2> GetAdjustmentItemData(Nullable<int> checkinItemItemId)
        {
            var checkinItemItemIdParameter = checkinItemItemId.HasValue ?
                new ObjectParameter("CheckinItemItemId", checkinItemItemId) :
                new ObjectParameter("CheckinItemItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdjustmentItemData_Result2>("GetAdjustmentItemData", checkinItemItemIdParameter);
        }
    
        public virtual ObjectResult<GetCheckinItemData_Result3> GetCheckinItemData(Nullable<int> checkinItemItemId)
        {
            var checkinItemItemIdParameter = checkinItemItemId.HasValue ?
                new ObjectParameter("CheckinItemItemId", checkinItemItemId) :
                new ObjectParameter("CheckinItemItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCheckinItemData_Result3>("GetCheckinItemData", checkinItemItemIdParameter);
        }
    
        public virtual ObjectResult<GetTransferItemData_Result3> GetTransferItemData(Nullable<int> transferItemId)
        {
            var transferItemIdParameter = transferItemId.HasValue ?
                new ObjectParameter("TransferItemId", transferItemId) :
                new ObjectParameter("TransferItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTransferItemData_Result3>("GetTransferItemData", transferItemIdParameter);
        }
    
        public virtual ObjectResult<GetTCheckinList_Result> GetTCheckinList(Nullable<int> itemId, Nullable<int> warehouseId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var warehouseIdParameter = warehouseId.HasValue ?
                new ObjectParameter("WarehouseId", warehouseId) :
                new ObjectParameter("WarehouseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTCheckinList_Result>("GetTCheckinList", itemIdParameter, warehouseIdParameter);
        }
    
        public virtual ObjectResult<ItemStockLedgerReportData_Result> ItemStockLedgerReportData(string searchValue, string tsearchValue, string asearchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            var tsearchValueParameter = tsearchValue != null ?
                new ObjectParameter("TsearchValue", tsearchValue) :
                new ObjectParameter("TsearchValue", typeof(string));
    
            var asearchValueParameter = asearchValue != null ?
                new ObjectParameter("AsearchValue", asearchValue) :
                new ObjectParameter("AsearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ItemStockLedgerReportData_Result>("ItemStockLedgerReportData", searchValueParameter, tsearchValueParameter, asearchValueParameter);
        }
    
        public virtual ObjectResult<ItemStockLedgerDetailReportData_Result1> ItemStockLedgerDetailReportData(Nullable<int> itemId, Nullable<int> warehouseId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var warehouseIdParameter = warehouseId.HasValue ?
                new ObjectParameter("WarehouseId", warehouseId) :
                new ObjectParameter("WarehouseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ItemStockLedgerDetailReportData_Result1>("ItemStockLedgerDetailReportData", itemIdParameter, warehouseIdParameter);
        }
    
        public virtual ObjectResult<WarehouseAccess_Result> WarehouseAccess(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("SearchValue", searchValue) :
                new ObjectParameter("SearchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WarehouseAccess_Result>("WarehouseAccess", searchValueParameter);
        }
    
        public virtual ObjectResult<CheckinViewData_Result2> CheckinViewData(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckinViewData_Result2>("CheckinViewData", idParameter);
        }
    
        public virtual ObjectResult<AdjustmentViewData_Result> AdjustmentViewData(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdjustmentViewData_Result>("AdjustmentViewData", idParameter);
        }
    
        public virtual ObjectResult<CheckoutViewData_Result> CheckoutViewData(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckoutViewData_Result>("CheckoutViewData", idParameter);
        }
    
        public virtual ObjectResult<TransferViewData_Result> TransferViewData(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TransferViewData_Result>("TransferViewData", idParameter);
        }
    }
}
