using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Inventories.Models
{
    public class ResourceFile
    {
        public string Dashboard { get; set; }
        public string Welcome { get; set; }

        public string Admin { get; set; }
        public string User_List { get; set; }
        public string User { get; set; }
        public string Create_New_User { get; set; }
        public string Username { get; set; }

        public string Name { get; set; }
        public string Phone_Number  { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public string Password { get; set; }
        public string Action { get; set; }
        public string Edit { get; set; }
        public string Delete { get; set; }
        public string User_Name { get; set; }
        public string Warehouse { get; set; }
        public string Save { get; set; }
        public string Cancel { get; set; }
        public string List { get; set; }
        public string Create_User { get; set; }
        public string Create { get; set; }
        public string New { get; set; }
        public string Excel { get; set; }
        public string ROLES { get; set; }
        public string PERMISSIONS { get; set; }
        public string Add_Roles { get; set; }
        public string Add { get; set; }
        public string Module { get; set; }
        public string Access { get; set; }
        public string Permission { get; set; }
        public string APActivePTS { get; set; }
        public string Save_Changes { get; set; }
        public string Changes { get; set; }
        public string Phone { get; set; }
        public string Details { get; set; }
        public string Contact { get; set; }
        public string Contact_List { get; set; }
        public string Create_New_Contact { get; set; }
        public string Categories_List { get; set; }
        public string Categories { get; set; }
        public string Create_New_Category { get; set; }
        public string Category { get; set; }
        public string Code { get; set; }
        public string Base_Unit { get; set; }
        public string Base { get; set; }
        public string Unit { get; set; }
        public string Formula { get; set; }
        public string Operator { get; set; }
        public string Select { get; set; }
        public string Multiply { get; set; }
        public string Divide { get; set; }
        public string Plus { get; set; }
        public string Minus { get; set; }
        public string Operation_Value { get; set; }
        public string Operation { get; set; }
        public string Value { get; set; }
        public string Address { get; set; }
        public string Warehouse_List { get; set; }
        public string Create_New_Warehouse { get; set; }
        public string Logo { get; set; }
        public string Item_List { get; set; }
        public string Item { get; set; }
        public string Create_New_Item { get; set; }
        public string Barcode_Symbology { get; set; }
        public string Rack_Location { get; set; }
        public string Rack { get; set; }
        public string Location { get; set; }
        public string Track_Quantity { get; set; }
        public string Track { get; set; }
        public string Quantity { get; set; }
        public string Alert_on_Low_Stock { get; set; }
        public string Alert { get; set; }
        public string on { get; set; }
        public string Low { get; set; }
        public string Stock { get; set; }
        public string Create_Item { get; set; }
        public string Create_Warehouse { get; set; }
        public string Unit_List { get; set; }
        public string Create_Unit { get; set; }
        public string Create_Category { get; set; }
        public string Create_Contact { get; set; }
        public string _Create_New_Unit { get; set; }
        public string Transfer_List { get; set; }
        public string Create_New_Transfer { get; set; }
        public string Transfer_Date { get; set; }
        public string Transfer { get; set; }
        public string Create_Transfer { get; set; }
        public string Transfer_Number { get; set; }
        public string Number { get; set; }

        public string Date { get; set; }
        public string From_Warehouse { get; set; }
        public string Reference { get; set; }
        public string To_Warehouse { get; set; }
        public string Scan_barcode_or_search_items { get; set; }

        public string Scan { get; set; }
        public string barcode { get; set; }
        public string or { get; set; }
        public string search { get; set; }
        public string items { get; set; }
        public string Batch { get; set; }
        public string Select_Batch { get; set; }
        public string Available_Quantity { get; set; }
        public string Transfers { get; set; }
        public string Checkin_List { get; set; }
        public string Checkin { get; set; }
        public string Create_New_Checkin { get; set; }
        public string Checkin_Number { get; set; }
        public string Create_Checkin { get; set; }
        public string Checkins { get; set; }
        public string Weight { get; set; }
        public string Checkout_List { get; set; }
        public string Checkout { get; set; }
        public string Create_New_Checkout { get; set; }
        public string Create_Checkout { get; set; }
        public string Checkout_Date { get; set; }
        public string Checkin_Date { get; set; }
        public string Checkout_Number { get; set; }
        public string Checkouts { get; set; }
        public string Adjustment_List { get; set; }
        public string Adjustment { get; set; }
        public string Adjustment_Date { get; set; }
        public string Create_New_Adjustment { get; set; }
        public string Create_Adjustment { get; set; }
        public string Adjustment_Number { get; set; }
        public string Adjustments { get; set; }
        public string Type { get; set; }
        public string Warehouses { get; set; }
        public string Contacts { get; set; }
        public string Units { get; set; }
        public string Users { get; set; }
        public string Report_Links { get; set; }
        public string Report { get; set; }
        public string Links { get; set; }
        public string Please_click_to_see_the_report { get; set; }
        public string Please { get; set; }
        public string click { get; set; }
        public string to { get; set; }
        public string None { get; set; }
        public string see { get; set; }
        public string the { get; set; }
        public string Checkin_Report { get; set; }
        public string Checkout_Report { get; set; }
        public string Transfer_Report { get; set; }
        public string Adjustment_Report { get; set; }
        public string Toggle_Form { get; set; }
        public string Inventories { get; set; }
        public string For { get; set; }
        public string Item_Category { get; set; }
        public string Item_Unit { get; set; }
        public string Category_Name { get; set; }
        public string Item_Name { get; set; }
        public string Qty { get; set; }
        public string Warehouse_Name { get; set; }
        public string Item_Stock_Ledger_Report { get; set; }
        public string Ledger { get; set; }
        public string Item_Stock_Ledger_Detail_Report { get; set; }
        public string Voucher_Number { get; set; }
        public string Logout { get; set; }
        public string Email_Settings { get; set; }
        public string Settings { get; set; }
        public string has_less_Quantity_than { get; set; }
        public string has { get; set; }
        public string less { get; set; }
        public string than { get; set; }
        public string Notifications { get; set; }
        public string Main { get; set; }
        public string Login { get; set; }
        public string Access_to_our_dashboard { get; set; }
        public string Our { get; set; }
        public string Forgot_Password { get; set; }
        public string Forgot { get; set; }
        public string Enter_your_email_to_get_a_password_reset_link { get; set; }
        public string Enter { get; set; }
        public string your { get; set; }
        public string get { get; set; }
        public string a { get; set; }
        public string reset { get; set; }
        public string link { get; set; }
        public string Remember_your_password { get; set; }
        public string Remember { get; set; }
        public string Select_date_range { get; set; }
        public string Reset_Password { get; set; }
        public string Are_you_sure_want_to_delete_this { get; set; }
        public string Close { get; set; }
        public string Meter { get; set; }
        public string Piece { get; set; }
        public string Kilogram { get; set; }
        public string Dozen { get; set; }
        public string Damage { get; set; }
        public string Addition { get; set; }
        public string Subtraction { get; set; }
        public string Total_Records { get; set; }
        public string Please_review_the_total_records_below { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        public string Start_Created_At { get; set; }
        public string End_Created_At { get; set; }
        public string New_Password_and_Confirm_Password_not_Matched { get; set; }
        public string Confirm { get; set; }
        public string Error { get; set; }
        public string Change { get; set; }
        
    }
}