//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlertQty
    {
        public int AlertQtyId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<bool> Notify { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
    
        public virtual tblItem tblItem { get; set; }
    }
}
