//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItem()
        {
            this.tblTransferItems = new HashSet<tblTransferItem>();
            this.tblCheckinItems = new HashSet<tblCheckinItem>();
            this.tblCheckoutItems = new HashSet<tblCheckoutItem>();
            this.tblAdjustmentItems = new HashSet<tblAdjustmentItem>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Unit { get; set; }
        public string BarcodeSymbology { get; set; }
        public string RackLocation { get; set; }
        public string SKU { get; set; }
        public string Details { get; set; }
        public Nullable<int> Alertonlowstock { get; set; }
        public Nullable<bool> TrackQuantity { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransferItem> tblTransferItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCheckinItem> tblCheckinItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCheckoutItem> tblCheckoutItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdjustmentItem> tblAdjustmentItems { get; set; }
    }
}
