//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventories.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to our dashboard.
        /// </summary>
        public static string Access_to_our_dashboard {
            get {
                return ResourceManager.GetString("Access_to_our_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Roles.
        /// </summary>
        public static string Add_Roles {
            get {
                return ResourceManager.GetString("Add_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        public static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string Adjustment {
            get {
                return ResourceManager.GetString("Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Date.
        /// </summary>
        public static string Adjustment_Date {
            get {
                return ResourceManager.GetString("Adjustment_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment List.
        /// </summary>
        public static string Adjustment_List {
            get {
                return ResourceManager.GetString("Adjustment_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Number.
        /// </summary>
        public static string Adjustment_Number {
            get {
                return ResourceManager.GetString("Adjustment_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Report.
        /// </summary>
        public static string Adjustment_Report {
            get {
                return ResourceManager.GetString("Adjustment_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments.
        /// </summary>
        public static string Adjustments {
            get {
                return ResourceManager.GetString("Adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert on Low Stock.
        /// </summary>
        public static string Alert_on_Low_Stock {
            get {
                return ResourceManager.GetString("Alert_on_Low_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and current Qty is.
        /// </summary>
        public static string and_current_Qty_is {
            get {
                return ResourceManager.GetString("and_current_Qty_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this.
        /// </summary>
        public static string Are_you_sure_want_to_delete_this {
            get {
                return ResourceManager.GetString("Are_you_sure_want_to_delete_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Quantity.
        /// </summary>
        public static string Available_Quantity {
            get {
                return ResourceManager.GetString("Available_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barcode.
        /// </summary>
        public static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Symbology.
        /// </summary>
        public static string Barcode_Symbology {
            get {
                return ResourceManager.GetString("Barcode_Symbology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Unit.
        /// </summary>
        public static string Base_Unit {
            get {
                return ResourceManager.GetString("Base_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories List.
        /// </summary>
        public static string Categories_List {
            get {
                return ResourceManager.GetString("Categories_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin.
        /// </summary>
        public static string Checkin {
            get {
                return ResourceManager.GetString("Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin Date.
        /// </summary>
        public static string Checkin_Date {
            get {
                return ResourceManager.GetString("Checkin_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin List.
        /// </summary>
        public static string Checkin_List {
            get {
                return ResourceManager.GetString("Checkin_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin Number.
        /// </summary>
        public static string Checkin_Number {
            get {
                return ResourceManager.GetString("Checkin_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin Report.
        /// </summary>
        public static string Checkin_Report {
            get {
                return ResourceManager.GetString("Checkin_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkins.
        /// </summary>
        public static string Checkins {
            get {
                return ResourceManager.GetString("Checkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Date.
        /// </summary>
        public static string Checkout_Date {
            get {
                return ResourceManager.GetString("Checkout_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout List.
        /// </summary>
        public static string Checkout_List {
            get {
                return ResourceManager.GetString("Checkout_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Number.
        /// </summary>
        public static string Checkout_Number {
            get {
                return ResourceManager.GetString("Checkout_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Report.
        /// </summary>
        public static string Checkout_Report {
            get {
                return ResourceManager.GetString("Checkout_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkouts.
        /// </summary>
        public static string Checkouts {
            get {
                return ResourceManager.GetString("Checkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click.
        /// </summary>
        public static string click {
            get {
                return ResourceManager.GetString("click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact List.
        /// </summary>
        public static string Contact_List {
            get {
                return ResourceManager.GetString("Contact_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Adjustment.
        /// </summary>
        public static string Create_Adjustment {
            get {
                return ResourceManager.GetString("Create_Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string Create_Category {
            get {
                return ResourceManager.GetString("Create_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Checkin.
        /// </summary>
        public static string Create_Checkin {
            get {
                return ResourceManager.GetString("Create_Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Checkout.
        /// </summary>
        public static string Create_Checkout {
            get {
                return ResourceManager.GetString("Create_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact.
        /// </summary>
        public static string Create_Contact {
            get {
                return ResourceManager.GetString("Create_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Item.
        /// </summary>
        public static string Create_Item {
            get {
                return ResourceManager.GetString("Create_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Adjustment.
        /// </summary>
        public static string Create_New_Adjustment {
            get {
                return ResourceManager.GetString("Create_New_Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Category.
        /// </summary>
        public static string Create_New_Category {
            get {
                return ResourceManager.GetString("Create_New_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Checkin.
        /// </summary>
        public static string Create_New_Checkin {
            get {
                return ResourceManager.GetString("Create_New_Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Checkout.
        /// </summary>
        public static string Create_New_Checkout {
            get {
                return ResourceManager.GetString("Create_New_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Contact.
        /// </summary>
        public static string Create_New_Contact {
            get {
                return ResourceManager.GetString("Create_New_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Item.
        /// </summary>
        public static string Create_New_Item {
            get {
                return ResourceManager.GetString("Create_New_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Transfer.
        /// </summary>
        public static string Create_New_Transfer {
            get {
                return ResourceManager.GetString("Create_New_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Unit.
        /// </summary>
        public static string Create_New_Unit {
            get {
                return ResourceManager.GetString("Create_New_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string Create_New_User {
            get {
                return ResourceManager.GetString("Create_New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Warehouse.
        /// </summary>
        public static string Create_New_Warehouse {
            get {
                return ResourceManager.GetString("Create_New_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Transfer.
        /// </summary>
        public static string Create_Transfer {
            get {
                return ResourceManager.GetString("Create_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Unit.
        /// </summary>
        public static string Create_Unit {
            get {
                return ResourceManager.GetString("Create_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string Create_User {
            get {
                return ResourceManager.GetString("Create_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Warehouse.
        /// </summary>
        public static string Create_Warehouse {
            get {
                return ResourceManager.GetString("Create_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        public static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dozen.
        /// </summary>
        public static string Dozen {
            get {
                return ResourceManager.GetString("Dozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string Email_Settings {
            get {
                return ResourceManager.GetString("Email_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Created At.
        /// </summary>
        public static string End_Created_At {
            get {
                return ResourceManager.GetString("End_Created_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string End_Date {
            get {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to get a password reset link.
        /// </summary>
        public static string Enter_your_email_to_get_a_password_reset_link {
            get {
                return ResourceManager.GetString("Enter_your_email_to_get_a_password_reset_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Warehouse.
        /// </summary>
        public static string From_Warehouse {
            get {
                return ResourceManager.GetString("From_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get.
        /// </summary>
        public static string get {
            get {
                return ResourceManager.GetString("get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has.
        /// </summary>
        public static string has {
            get {
                return ResourceManager.GetString("has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has less Quantity than.
        /// </summary>
        public static string has_less_Quantity_than {
            get {
                return ResourceManager.GetString("has_less_Quantity_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover Color.
        /// </summary>
        public static string Hover_Color {
            get {
                return ResourceManager.GetString("Hover_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string Inventories {
            get {
                return ResourceManager.GetString("Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Category.
        /// </summary>
        public static string Item_Category {
            get {
                return ResourceManager.GetString("Item_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string Item_List {
            get {
                return ResourceManager.GetString("Item_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Stock Ledger Detail Report.
        /// </summary>
        public static string Item_Stock_Ledger_Detail_Report {
            get {
                return ResourceManager.GetString("Item_Stock_Ledger_Detail_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Stock Ledger Report.
        /// </summary>
        public static string Item_Stock_Ledger_Report {
            get {
                return ResourceManager.GetString("Item_Stock_Ledger_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Unit.
        /// </summary>
        public static string Item_Unit {
            get {
                return ResourceManager.GetString("Item_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        public static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger.
        /// </summary>
        public static string Ledger {
            get {
                return ResourceManager.GetString("Ledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less.
        /// </summary>
        public static string less {
            get {
                return ResourceManager.GetString("less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        public static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        public static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm Password not Matched.
        /// </summary>
        public static string New_Password_and_Confirm_Password_not_Matched {
            get {
                return ResourceManager.GetString("New_Password_and_Confirm_Password_not_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Color.
        /// </summary>
        public static string Normal_Color {
            get {
                return ResourceManager.GetString("Normal_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Value.
        /// </summary>
        public static string Operation_Value {
            get {
                return ResourceManager.GetString("Operation_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMISSIONS.
        /// </summary>
        public static string PERMISSIONS {
            get {
                return ResourceManager.GetString("PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece.
        /// </summary>
        public static string Piece {
            get {
                return ResourceManager.GetString("Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click to see the report.
        /// </summary>
        public static string Please_click_to_see_the_report {
            get {
                return ResourceManager.GetString("Please_click_to_see_the_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the total records below.
        /// </summary>
        public static string Please_review_the_total_records_below {
            get {
                return ResourceManager.GetString("Please_review_the_total_records_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        public static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        public static string Rack {
            get {
                return ResourceManager.GetString("Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack Location.
        /// </summary>
        public static string Rack_Location {
            get {
                return ResourceManager.GetString("Rack_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember your password.
        /// </summary>
        public static string Remember_your_password {
            get {
                return ResourceManager.GetString("Remember_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Links.
        /// </summary>
        public static string Report_Links {
            get {
                return ResourceManager.GetString("Report_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string ROLES {
            get {
                return ResourceManager.GetString("ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan barcode or search items.
        /// </summary>
        public static string Scan_barcode_or_search_items {
            get {
                return ResourceManager.GetString("Scan_barcode_or_search_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see.
        /// </summary>
        public static string see {
            get {
                return ResourceManager.GetString("see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Batch.
        /// </summary>
        public static string Select_Batch {
            get {
                return ResourceManager.GetString("Select_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Created At.
        /// </summary>
        public static string Start_Created_At {
            get {
                return ResourceManager.GetString("Start_Created_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_Date {
            get {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        public static string Subtraction {
            get {
                return ResourceManager.GetString("Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to than.
        /// </summary>
        public static string than {
            get {
                return ResourceManager.GetString("than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string the {
            get {
                return ResourceManager.GetString("the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Warehouse.
        /// </summary>
        public static string To_Warehouse {
            get {
                return ResourceManager.GetString("To_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Form.
        /// </summary>
        public static string Toggle_Form {
            get {
                return ResourceManager.GetString("Toggle_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        public static string Total_Records {
            get {
                return ResourceManager.GetString("Total_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Quantity.
        /// </summary>
        public static string Track_Quantity {
            get {
                return ResourceManager.GetString("Track_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Date.
        /// </summary>
        public static string Transfer_Date {
            get {
                return ResourceManager.GetString("Transfer_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer List.
        /// </summary>
        public static string Transfer_List {
            get {
                return ResourceManager.GetString("Transfer_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Number.
        /// </summary>
        public static string Transfer_Number {
            get {
                return ResourceManager.GetString("Transfer_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Report.
        /// </summary>
        public static string Transfer_Report {
            get {
                return ResourceManager.GetString("Transfer_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit List.
        /// </summary>
        public static string Unit_List {
            get {
                return ResourceManager.GetString("Unit_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string User_List {
            get {
                return ResourceManager.GetString("User_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Number.
        /// </summary>
        public static string Voucher_Number {
            get {
                return ResourceManager.GetString("Voucher_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse List.
        /// </summary>
        public static string Warehouse_List {
            get {
                return ResourceManager.GetString("Warehouse_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Name.
        /// </summary>
        public static string Warehouse_Name {
            get {
                return ResourceManager.GetString("Warehouse_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        public static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your.
        /// </summary>
        public static string your {
            get {
                return ResourceManager.GetString("your", resourceCulture);
            }
        }
    }
}
